name: go-releaser

permissions:
  contents: write
  id-token: write
  packages: write

on:
  push:
    tags: ['v*']

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
          cache: true

      - name: Install Linux and Windows Toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 \
            gcc-mingw-w64-i686 g++-mingw-w64-i686
      

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUBTOKEN }}
